# Configuration for probot-auto-labeler - https://github.com/probot/autolabeler

# label: file | path
android: ["/drago_inappwebview", "*.dart", "*.kt", "*.java", "*gradle*", "AndroidManifest.xml"]
iOS: ["/drago_inappwebview", "*.dart", "*.swift", "*.h", "*.m", "*.plist", "*.storyboard", "*.xcconfig", Podfile*"]
macOS: ["/drago_inappwebview", "*.dart", "*.swift", "*.h", "*.m", "*.plist", "*.storyboard", "*.xcconfig", Podfile*"]
windows: ["/drago_inappwebview", "*.dart", "*.cs", "*.c", "*.cpp", "*.h", "CMakeLists.txt"]
linux: ["/drago_inappwebview", "*.dart", "*.c", "*.h", "*.cpp", "*.cmake", "*.makefile", "CMakeLists.txt"]
web: ["/drago_inappwebview", "*.dart", "*.html", "*.js", "*.css"]
platform_interface: ["/drago_inappwebview_platform_interface", "*.dart"]
plugin: ["/drago_inappwebview", "*.dart"]
documentation: ["*.md"]
legal: ["LICENSE*", "NOTICES*"]
